[[headers]]
for = "/*"

[headers.values]
Cross-Origin-Embedder-Policy = "credentialless"
Cross-Origin-Opener-Policy = "same-origin"
Access-Control-Allow-Origin = "*"

[build]
command = "npm run build"
publish = "dist"